apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/idhananjay14/gitops-platform.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
